/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type CreateBookingPaymentRequest = {
    /**
     * The ID of the booking to pay for.
     */
    bookingId: string;
    bookingPayment: components.BookingPayment;
};

/**
 * Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase.
 */
export const Currency = {
    Bam: "bam",
    Bgn: "bgn",
    Chf: "chf",
    Eur: "eur",
    Gbp: "gbp",
    Nok: "nok",
    Sek: "sek",
    Try: "try",
} as const;
/**
 * Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase.
 */
export type Currency = ClosedEnum<typeof Currency>;

/**
 * The type of entity that holds the account. This can be either `individual` or `company`.
 */
export const AccountType = {
    Individual: "individual",
    Company: "company",
} as const;
/**
 * The type of entity that holds the account. This can be either `individual` or `company`.
 */
export type AccountType = ClosedEnum<typeof AccountType>;

/**
 * A bank account to take payment from. Must be able to make payments in the currency specified in the payment.
 */
export type BankAccount = {
    object?: "bank_account" | undefined;
    name: string;
    /**
     * The account number for the bank account, in string form. Must be a current account.
     */
    number: string;
    /**
     * The sort code for the bank account, in string form. Must be a six-digit number.
     */
    sortCode?: string | undefined;
    /**
     * The type of entity that holds the account. This can be either `individual` or `company`.
     */
    accountType: AccountType;
    /**
     * The name of the bank associated with the routing number.
     */
    bankName: string;
    /**
     * Two-letter country code (ISO 3166-1 alpha-2).
     */
    country: string;
};

/**
 * A card (debit or credit) to take payment from.
 */
export type Card = {
    object?: "card" | undefined;
    /**
     * Cardholder's full name as it appears on the card.
     */
    name: string;
    /**
     * The card number, as a string without any separators. On read all but the last four digits will be masked for security.
     */
    number: string;
    /**
     * Two-digit number representing the card's expiration month.
     */
    expMonth: number;
    /**
     * Four-digit number representing the card's expiration year.
     */
    expYear: number;
    addressCity?: string | undefined;
    addressCountry: string;
    addressPostCode?: string | undefined;
};

/**
 * The payment source to take the payment from. This can be a card or a bank account. Some of these properties will be hidden on read to protect PII leaking.
 */
export type Source = BankAccount | Card;

/**
 * The status of the payment, one of `pending`, `succeeded`, or `failed`.
 */
export const Status = {
    Pending: "pending",
    Succeeded: "succeeded",
    Failed: "failed",
} as const;
/**
 * The status of the payment, one of `pending`, `succeeded`, or `failed`.
 */
export type Status = ClosedEnum<typeof Status>;

/**
 * Payment successful
 */
export type CreateBookingPaymentResponseBody = {
    /**
     * Unique identifier for the payment. This will be a unique identifier for the payment, and is used to reference the payment in other objects.
     */
    id?: string | undefined;
    /**
     * Amount intended to be collected by this payment. A positive decimal figure describing the amount to be collected.
     */
    amount?: number | undefined;
    /**
     * Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase.
     */
    currency?: Currency | undefined;
    /**
     * The payment source to take the payment from. This can be a card or a bank account. Some of these properties will be hidden on read to protect PII leaking.
     */
    source?: BankAccount | Card | undefined;
    /**
     * The status of the payment, one of `pending`, `succeeded`, or `failed`.
     */
    status?: Status | undefined;
    links?: components.LinksBooking | undefined;
};

export type CreateBookingPaymentResponse = {
    headers: { [k: string]: Array<string> };
    result: CreateBookingPaymentResponseBody;
};

/** @internal */
export const CreateBookingPaymentRequest$inboundSchema: z.ZodType<
    CreateBookingPaymentRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        bookingId: z.string(),
        BookingPayment: components.BookingPayment$inboundSchema,
    })
    .transform((v) => {
        return remap$(v, {
            BookingPayment: "bookingPayment",
        });
    });

/** @internal */
export type CreateBookingPaymentRequest$Outbound = {
    bookingId: string;
    BookingPayment: components.BookingPayment$Outbound;
};

/** @internal */
export const CreateBookingPaymentRequest$outboundSchema: z.ZodType<
    CreateBookingPaymentRequest$Outbound,
    z.ZodTypeDef,
    CreateBookingPaymentRequest
> = z
    .object({
        bookingId: z.string(),
        bookingPayment: components.BookingPayment$outboundSchema,
    })
    .transform((v) => {
        return remap$(v, {
            bookingPayment: "BookingPayment",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateBookingPaymentRequest$ {
    /** @deprecated use `CreateBookingPaymentRequest$inboundSchema` instead. */
    export const inboundSchema = CreateBookingPaymentRequest$inboundSchema;
    /** @deprecated use `CreateBookingPaymentRequest$outboundSchema` instead. */
    export const outboundSchema = CreateBookingPaymentRequest$outboundSchema;
    /** @deprecated use `CreateBookingPaymentRequest$Outbound` instead. */
    export type Outbound = CreateBookingPaymentRequest$Outbound;
}

/** @internal */
export const Currency$inboundSchema: z.ZodNativeEnum<typeof Currency> = z.nativeEnum(Currency);

/** @internal */
export const Currency$outboundSchema: z.ZodNativeEnum<typeof Currency> = Currency$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Currency$ {
    /** @deprecated use `Currency$inboundSchema` instead. */
    export const inboundSchema = Currency$inboundSchema;
    /** @deprecated use `Currency$outboundSchema` instead. */
    export const outboundSchema = Currency$outboundSchema;
}

/** @internal */
export const AccountType$inboundSchema: z.ZodNativeEnum<typeof AccountType> =
    z.nativeEnum(AccountType);

/** @internal */
export const AccountType$outboundSchema: z.ZodNativeEnum<typeof AccountType> =
    AccountType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AccountType$ {
    /** @deprecated use `AccountType$inboundSchema` instead. */
    export const inboundSchema = AccountType$inboundSchema;
    /** @deprecated use `AccountType$outboundSchema` instead. */
    export const outboundSchema = AccountType$outboundSchema;
}

/** @internal */
export const BankAccount$inboundSchema: z.ZodType<BankAccount, z.ZodTypeDef, unknown> = z
    .object({
        object: z.literal("bank_account").optional(),
        name: z.string(),
        number: z.string(),
        sort_code: z.string().optional(),
        account_type: AccountType$inboundSchema,
        bank_name: z.string(),
        country: z.string(),
    })
    .transform((v) => {
        return remap$(v, {
            sort_code: "sortCode",
            account_type: "accountType",
            bank_name: "bankName",
        });
    });

/** @internal */
export type BankAccount$Outbound = {
    object: "bank_account";
    name: string;
    number: string;
    sort_code?: string | undefined;
    account_type: string;
    bank_name: string;
    country: string;
};

/** @internal */
export const BankAccount$outboundSchema: z.ZodType<
    BankAccount$Outbound,
    z.ZodTypeDef,
    BankAccount
> = z
    .object({
        object: z.literal("bank_account").default("bank_account" as const),
        name: z.string(),
        number: z.string(),
        sortCode: z.string().optional(),
        accountType: AccountType$outboundSchema,
        bankName: z.string(),
        country: z.string(),
    })
    .transform((v) => {
        return remap$(v, {
            sortCode: "sort_code",
            accountType: "account_type",
            bankName: "bank_name",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace BankAccount$ {
    /** @deprecated use `BankAccount$inboundSchema` instead. */
    export const inboundSchema = BankAccount$inboundSchema;
    /** @deprecated use `BankAccount$outboundSchema` instead. */
    export const outboundSchema = BankAccount$outboundSchema;
    /** @deprecated use `BankAccount$Outbound` instead. */
    export type Outbound = BankAccount$Outbound;
}

/** @internal */
export const Card$inboundSchema: z.ZodType<Card, z.ZodTypeDef, unknown> = z
    .object({
        object: z.literal("card").optional(),
        name: z.string(),
        number: z.string(),
        exp_month: z.number().int(),
        exp_year: z.number().int(),
        address_city: z.string().optional(),
        address_country: z.string(),
        address_post_code: z.string().optional(),
    })
    .transform((v) => {
        return remap$(v, {
            exp_month: "expMonth",
            exp_year: "expYear",
            address_city: "addressCity",
            address_country: "addressCountry",
            address_post_code: "addressPostCode",
        });
    });

/** @internal */
export type Card$Outbound = {
    object: "card";
    name: string;
    number: string;
    exp_month: number;
    exp_year: number;
    address_city?: string | undefined;
    address_country: string;
    address_post_code?: string | undefined;
};

/** @internal */
export const Card$outboundSchema: z.ZodType<Card$Outbound, z.ZodTypeDef, Card> = z
    .object({
        object: z.literal("card").default("card" as const),
        name: z.string(),
        number: z.string(),
        expMonth: z.number().int(),
        expYear: z.number().int(),
        addressCity: z.string().optional(),
        addressCountry: z.string(),
        addressPostCode: z.string().optional(),
    })
    .transform((v) => {
        return remap$(v, {
            expMonth: "exp_month",
            expYear: "exp_year",
            addressCity: "address_city",
            addressCountry: "address_country",
            addressPostCode: "address_post_code",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Card$ {
    /** @deprecated use `Card$inboundSchema` instead. */
    export const inboundSchema = Card$inboundSchema;
    /** @deprecated use `Card$outboundSchema` instead. */
    export const outboundSchema = Card$outboundSchema;
    /** @deprecated use `Card$Outbound` instead. */
    export type Outbound = Card$Outbound;
}

/** @internal */
export const Source$inboundSchema: z.ZodType<Source, z.ZodTypeDef, unknown> = z.union([
    z.lazy(() => BankAccount$inboundSchema),
    z.lazy(() => Card$inboundSchema),
]);

/** @internal */
export type Source$Outbound = BankAccount$Outbound | Card$Outbound;

/** @internal */
export const Source$outboundSchema: z.ZodType<Source$Outbound, z.ZodTypeDef, Source> = z.union([
    z.lazy(() => BankAccount$outboundSchema),
    z.lazy(() => Card$outboundSchema),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Source$ {
    /** @deprecated use `Source$inboundSchema` instead. */
    export const inboundSchema = Source$inboundSchema;
    /** @deprecated use `Source$outboundSchema` instead. */
    export const outboundSchema = Source$outboundSchema;
    /** @deprecated use `Source$Outbound` instead. */
    export type Outbound = Source$Outbound;
}

/** @internal */
export const Status$inboundSchema: z.ZodNativeEnum<typeof Status> = z.nativeEnum(Status);

/** @internal */
export const Status$outboundSchema: z.ZodNativeEnum<typeof Status> = Status$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Status$ {
    /** @deprecated use `Status$inboundSchema` instead. */
    export const inboundSchema = Status$inboundSchema;
    /** @deprecated use `Status$outboundSchema` instead. */
    export const outboundSchema = Status$outboundSchema;
}

/** @internal */
export const CreateBookingPaymentResponseBody$inboundSchema: z.ZodType<
    CreateBookingPaymentResponseBody,
    z.ZodTypeDef,
    unknown
> = z.object({
    id: z.string().optional(),
    amount: z.number().optional(),
    currency: Currency$inboundSchema.optional(),
    source: z
        .union([z.lazy(() => BankAccount$inboundSchema), z.lazy(() => Card$inboundSchema)])
        .optional(),
    status: Status$inboundSchema.optional(),
    links: components.LinksBooking$inboundSchema.optional(),
});

/** @internal */
export type CreateBookingPaymentResponseBody$Outbound = {
    id?: string | undefined;
    amount?: number | undefined;
    currency?: string | undefined;
    source?: BankAccount$Outbound | Card$Outbound | undefined;
    status?: string | undefined;
    links?: components.LinksBooking$Outbound | undefined;
};

/** @internal */
export const CreateBookingPaymentResponseBody$outboundSchema: z.ZodType<
    CreateBookingPaymentResponseBody$Outbound,
    z.ZodTypeDef,
    CreateBookingPaymentResponseBody
> = z.object({
    id: z.string().optional(),
    amount: z.number().optional(),
    currency: Currency$outboundSchema.optional(),
    source: z
        .union([z.lazy(() => BankAccount$outboundSchema), z.lazy(() => Card$outboundSchema)])
        .optional(),
    status: Status$outboundSchema.optional(),
    links: components.LinksBooking$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateBookingPaymentResponseBody$ {
    /** @deprecated use `CreateBookingPaymentResponseBody$inboundSchema` instead. */
    export const inboundSchema = CreateBookingPaymentResponseBody$inboundSchema;
    /** @deprecated use `CreateBookingPaymentResponseBody$outboundSchema` instead. */
    export const outboundSchema = CreateBookingPaymentResponseBody$outboundSchema;
    /** @deprecated use `CreateBookingPaymentResponseBody$Outbound` instead. */
    export type Outbound = CreateBookingPaymentResponseBody$Outbound;
}

/** @internal */
export const CreateBookingPaymentResponse$inboundSchema: z.ZodType<
    CreateBookingPaymentResponse,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        Headers: z.record(z.array(z.string())),
        Result: z.lazy(() => CreateBookingPaymentResponseBody$inboundSchema),
    })
    .transform((v) => {
        return remap$(v, {
            Headers: "headers",
            Result: "result",
        });
    });

/** @internal */
export type CreateBookingPaymentResponse$Outbound = {
    Headers: { [k: string]: Array<string> };
    Result: CreateBookingPaymentResponseBody$Outbound;
};

/** @internal */
export const CreateBookingPaymentResponse$outboundSchema: z.ZodType<
    CreateBookingPaymentResponse$Outbound,
    z.ZodTypeDef,
    CreateBookingPaymentResponse
> = z
    .object({
        headers: z.record(z.array(z.string())),
        result: z.lazy(() => CreateBookingPaymentResponseBody$outboundSchema),
    })
    .transform((v) => {
        return remap$(v, {
            headers: "Headers",
            result: "Result",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateBookingPaymentResponse$ {
    /** @deprecated use `CreateBookingPaymentResponse$inboundSchema` instead. */
    export const inboundSchema = CreateBookingPaymentResponse$inboundSchema;
    /** @deprecated use `CreateBookingPaymentResponse$outboundSchema` instead. */
    export const outboundSchema = CreateBookingPaymentResponse$outboundSchema;
    /** @deprecated use `CreateBookingPaymentResponse$Outbound` instead. */
    export type Outbound = CreateBookingPaymentResponse$Outbound;
}
