/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { TrainTravelCore } from "../core.js";
import * as m$ from "../lib/matchers.js";
import { RequestOptions } from "../lib/sdks.js";
import { extractSecurity, resolveGlobalSecurity } from "../lib/security.js";
import { pathToFunc } from "../lib/url.js";
import {
    ConnectionError,
    InvalidRequestError,
    RequestAbortedError,
    RequestTimeoutError,
    UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import { SDKError } from "../models/errors/sdkerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import * as operations from "../models/operations/index.js";
import { Result } from "../types/fp.js";

export enum GetBookingsAcceptEnum {
    applicationJson = "application/json",
    applicationXml = "application/xml",
}

/**
 * List existing bookings
 *
 * @remarks
 * Returns a list of all trip bookings by the authenticated user.
 */
export async function bookingsGetBookings(
    client$: TrainTravelCore,
    options?: RequestOptions & { acceptHeaderOverride?: GetBookingsAcceptEnum }
): Promise<
    Result<
        operations.GetBookingsResponse,
        | SDKError
        | SDKValidationError
        | UnexpectedClientError
        | InvalidRequestError
        | RequestAbortedError
        | RequestTimeoutError
        | ConnectionError
    >
> {
    const path$ = pathToFunc("/bookings")();

    const headers$ = new Headers({
        Accept: options?.acceptHeaderOverride || "application/json;q=1, application/xml;q=0",
    });

    const oAuth2$ = await extractSecurity(client$.options$.oAuth2);
    const security$ = oAuth2$ == null ? {} : { oAuth2: oAuth2$ };
    const context = {
        operationID: "get-bookings",
        oAuth2Scopes: [],
        securitySource: client$.options$.oAuth2,
    };
    const securitySettings$ = resolveGlobalSecurity(security$);

    const requestRes = client$.createRequest$(
        context,
        {
            security: securitySettings$,
            method: "GET",
            path: path$,
            headers: headers$,
            timeoutMs: options?.timeoutMs || client$.options$.timeoutMs || -1,
        },
        options
    );
    if (!requestRes.ok) {
        return requestRes;
    }
    const request$ = requestRes.value;

    const doResult = await client$.do$(request$, {
        context,
        errorCodes: ["400", "401", "403", "429", "4XX", "500", "5XX"],
        retryConfig: options?.retries || client$.options$.retryConfig,
        retryCodes: options?.retryCodes || ["429", "500", "502", "503", "504"],
    });
    if (!doResult.ok) {
        return doResult;
    }
    const response = doResult.value;

    const responseFields$ = {
        HttpMeta: { Response: response, Request: request$ },
    };

    const [result$] = await m$.match<
        operations.GetBookingsResponse,
        | SDKError
        | SDKValidationError
        | UnexpectedClientError
        | InvalidRequestError
        | RequestAbortedError
        | RequestTimeoutError
        | ConnectionError
    >(
        m$.json(200, operations.GetBookingsResponse$inboundSchema, { hdrs: true, key: "Result" }),
        m$.bytes(200, operations.GetBookingsResponse$inboundSchema, {
            ctype: "application/xml",
            hdrs: true,
            key: "Result",
        }),
        m$.fail([400, 401, 403, 429, 500]),
        m$.fail(["4XX", "5XX"])
    )(response, { extraFields: responseFields$ });
    if (!result$.ok) {
        return result$;
    }

    return result$;
}
