/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { GetStationsAcceptEnum, stationsGetStations } from "../funcs/stationsGetStations.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export { GetStationsAcceptEnum } from "../funcs/stationsGetStations.js";

export class Stations extends ClientSDK {
    /**
     * Get a list of train stations
     *
     * @remarks
     * Returns a paginated and searchable list of all train stations.
     */
    async getStations(
        request: operations.GetStationsRequest,
        options?: RequestOptions & { acceptHeaderOverride?: GetStationsAcceptEnum }
    ): Promise<operations.GetStationsResponse> {
        return unwrapAsync(stationsGetStations(this, request, options));
    }
}
