/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { GetTripsAcceptEnum, tripsGetTrips } from "../funcs/tripsGetTrips.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export { GetTripsAcceptEnum } from "../funcs/tripsGetTrips.js";

export class Trips extends ClientSDK {
    /**
     * Get available train trips
     *
     * @remarks
     * Returns a list of available train trips between the specified origin and destination stations on the given date, and allows for filtering by bicycle and dog allowances.
     *
     */
    async getTrips(
        request: operations.GetTripsRequest,
        options?: RequestOptions & { acceptHeaderOverride?: GetTripsAcceptEnum }
    ): Promise<operations.GetTripsResponse> {
        return unwrapAsync(tripsGetTrips(this, request, options));
    }
}
