/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export type Booking = {
    /**
     * Unique identifier for the booking
     */
    id?: string | undefined;
    /**
     * Identifier of the booked trip
     */
    tripId?: string | undefined;
    /**
     * Name of the passenger
     */
    passengerName?: string | undefined;
    /**
     * Indicates whether the passenger has a bicycle.
     */
    hasBicycle?: boolean | undefined;
    /**
     * Indicates whether the passenger has a dog.
     */
    hasDog?: boolean | undefined;
};

/** @internal */
export const Booking$inboundSchema: z.ZodType<Booking, z.ZodTypeDef, unknown> = z
    .object({
        id: z.string().optional(),
        trip_id: z.string().optional(),
        passenger_name: z.string().optional(),
        has_bicycle: z.boolean().optional(),
        has_dog: z.boolean().optional(),
    })
    .transform((v) => {
        return remap$(v, {
            trip_id: "tripId",
            passenger_name: "passengerName",
            has_bicycle: "hasBicycle",
            has_dog: "hasDog",
        });
    });

/** @internal */
export type Booking$Outbound = {
    id?: string | undefined;
    trip_id?: string | undefined;
    passenger_name?: string | undefined;
    has_bicycle?: boolean | undefined;
    has_dog?: boolean | undefined;
};

/** @internal */
export const Booking$outboundSchema: z.ZodType<Booking$Outbound, z.ZodTypeDef, Booking> = z
    .object({
        id: z.string().optional(),
        tripId: z.string().optional(),
        passengerName: z.string().optional(),
        hasBicycle: z.boolean().optional(),
        hasDog: z.boolean().optional(),
    })
    .transform((v) => {
        return remap$(v, {
            tripId: "trip_id",
            passengerName: "passenger_name",
            hasBicycle: "has_bicycle",
            hasDog: "has_dog",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Booking$ {
    /** @deprecated use `Booking$inboundSchema` instead. */
    export const inboundSchema = Booking$inboundSchema;
    /** @deprecated use `Booking$outboundSchema` instead. */
    export const outboundSchema = Booking$outboundSchema;
    /** @deprecated use `Booking$Outbound` instead. */
    export type Outbound = Booking$Outbound;
}
