/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type LinksBooking = {
    booking?: string | undefined;
};

/** @internal */
export const LinksBooking$inboundSchema: z.ZodType<LinksBooking, z.ZodTypeDef, unknown> = z.object({
    booking: z.string().optional(),
});

/** @internal */
export type LinksBooking$Outbound = {
    booking?: string | undefined;
};

/** @internal */
export const LinksBooking$outboundSchema: z.ZodType<
    LinksBooking$Outbound,
    z.ZodTypeDef,
    LinksBooking
> = z.object({
    booking: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace LinksBooking$ {
    /** @deprecated use `LinksBooking$inboundSchema` instead. */
    export const inboundSchema = LinksBooking$inboundSchema;
    /** @deprecated use `LinksBooking$outboundSchema` instead. */
    export const outboundSchema = LinksBooking$outboundSchema;
    /** @deprecated use `LinksBooking$Outbound` instead. */
    export type Outbound = LinksBooking$Outbound;
}
